### ISSUE TITLE
AvatarOptimizer worker threads drop DSPy context and callback lineage

### ISSUE THREAD

**Issue by isaacbmiller** [stanfordnlp/dspy#10053]
## Reproduction

`AvatarOptimizer.thread_safe_evaluator()` changes DSPy semantics when work crosses its private thread pool:

```python
import dspy
from dspy.teleprompt.avatar_optimizer import AvatarOptimizer
from dspy.utils.callback import ACTIVE_CALL_ID, BaseCallback

GLOBAL_LM = object()
LOCAL_LM = object()


class Actor(dspy.Module):
    def forward(self, value):
        return dspy.Prediction(saw_local_lm=dspy.settings.lm is LOCAL_LM)


class Recorder(BaseCallback):
    def __init__(self):
        self.parents = []

    def on_module_start(self, call_id, instance, inputs):
        if isinstance(instance, Actor):
            self.parents.append(ACTIVE_CALL_ID.get())


# Bypass the separately broken constructor; see #7931 and the note below.
optimizer = object.__new__(AvatarOptimizer)
optimizer.metric = lambda example, prediction: float(prediction.saw_local_lm)

example = dspy.Example(value=1).with_inputs("value")
recorder = Recorder()
dspy.configure(lm=GLOBAL_LM, callbacks=[recorder])

token = ACTIVE_CALL_ID.set("parent")
try:
    with dspy.context(lm=LOCAL_LM):
        score = optimizer.thread_safe_evaluator([example], Actor(), num_threads=2)
finally:
    ACTIVE_CALL_ID.reset(token)

print("score", score)
print("actor_parent_ids", recorder.parents)
```

Output on current `main`:

```text
score 0.0
actor_parent_ids [None]
```

Expected:

```text
score 1.0
actor_parent_ids ['parent']
```

The worker therefore sees neither the request-scoped LM nor the causal callback parent. Callbacks installed through `dspy.context(callbacks=[...])` are also absent in the worker entirely.

## Root cause

`dspy/teleprompt/avatar_optimizer.py` creates a raw `ThreadPoolExecutor` and submits `process_example` directly:

```python
with ThreadPoolExecutor(max_workers=num_threads) as executor:
    futures = [
        executor.submit(self.process_example, actor, example, return_outputs)
        for example in devset
    ]
```

Python worker threads do not inherit DSPy's `ContextVar` state. Avatar bypasses the context-aware `ParallelExecutor` used by `Evaluate`, `dspy.Parallel`, and `Module.batch`, so it loses both `dspy.context(...)` overrides and callback ancestry.

## Desired fix

Run Avatar evaluation through `ParallelExecutor`, with straggler resubmission disabled to preserve the current at-most-once execution contract.

Preserve:

- input-order results;
- `return_outputs` behavior;
- average-score calculation;
- the existing exception-to-zero behavior; and
- no duplicate actor or LM calls.

Once #10043 lands, the shared boundary will transport callback ancestry as well as DSPy settings. Avoid a separate Avatar-specific `ContextVar` implementation.

Add regression coverage proving parity for one and multiple threads:

1. Workers observe a surrounding `dspy.context(...)`.
2. Actor callbacks inherit the active caller/optimizer call ID.
3. Result ordering and return shapes remain unchanged.

## Compatibility and downsides

The intended observable changes are:

- scoped DSPy settings now take precedence over global settings inside Avatar workers; and
- actor callbacks become children of the invoking optimizer rather than unrelated roots.

Using `ParallelExecutor` may change progress-bar output. Straggler retries should remain disabled because Avatar actor calls can have external effects and must not be duplicated.

## Existing Avatar breakage

Normal `Avatar` and `AvatarOptimizer` construction currently references the removed `dspy.TypedPredictor` and raises:

```text
AttributeError: module 'dspy' has no attribute 'TypedPredictor'
```

That constructor regression is already tracked in #7931. There are currently no Avatar tests under `tests/`, despite Avatar remaining exported and recommended in the optimizer documentation. Repairing the constructor should be handled explicitly rather than silently bundled into this thread-context issue.
